"""changed varchar to nullable true

Revision ID: 4f12a076cc86
Revises: d9cc959b8e87
Create Date: 2025-05-08 18:06:02.476691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f12a076cc86'
down_revision: Union[str, None] = 'd9cc959b8e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('contact', 'company',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'company',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('contact', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
